"""create tables

Revision ID: 83f45a58a1e9
Revises: c3462914d419
Create Date: 2026-09-04 16:00:28.227328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f45a58a1e9'
down_revision: Union[str, Sequence[str], None] = 'c3462914d419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('seats', sa.SmallInteger(), server_default='2', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pos_x', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pos_y', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('FREE', 'OCCUPIED', name='table_status'), server_default='FREE', nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'label', name='uniq_tables_venue_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    sa.Enum(name='table_status').drop(op.get_bind())
    # ### end Alembic commands ###
