"""add staff_assignments

Revision ID: 9374a1775109
Revises: de29d6d02b56
Create Date: 2026-09-15 12:41:08.915449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9374a1775109'
down_revision: Union[str, Sequence[str], None] = 'de29d6d02b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_assignments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'venue_id', name='unique_staff_assignments_user_venue')
    )
    # Hand-edited: autogenerate emitted drop_constraint + create_unique_constraint, which
    # rebuilds the backing index for nothing. A rename is a metadata-only operation.
    op.execute(
        "ALTER TABLE tables RENAME CONSTRAINT uniq_tables_venue_label "
        "TO unique_tables_venue_label"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE tables RENAME CONSTRAINT unique_tables_venue_label "
        "TO uniq_tables_venue_label"
    )
    op.drop_table('staff_assignments')
    # ### end Alembic commands ###
