"""Add status_events + status_source enum

Revision ID: de29d6d02b56
Revises: 83f45a58a1e9
Create Date: 2026-09-08 11:31:41.904875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'de29d6d02b56'
down_revision: Union[str, Sequence[str], None] = '83f45a58a1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # table_status already exists (created in 83f45a58a1e9 for `tables`), so reference it
    # with create_type=False -- otherwise this migration emits a duplicate CREATE TYPE.
    table_status = postgresql.ENUM('FREE', 'OCCUPIED', name='table_status', create_type=False)
    op.create_table('status_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('table_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', table_status, nullable=True),
    sa.Column('new_status', table_status, nullable=False),
    sa.Column('source', sa.Enum('STAFF_MANUAL', 'SYSTEM', name='status_source'), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_events_table_time', 'status_events', ['table_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status_events_table_time', table_name='status_events')
    op.drop_table('status_events')
    # Drop the type this migration created. NOT table_status -- `tables` still uses it.
    op.execute("DROP TYPE status_source")
    # ### end Alembic commands ###
